updated:Readme.md example table updated
LeeWannacott/table-sort-js pull request #12
Opened 2021-02-08 17:18 UTC by anupshrestha11

2021-02-09 00:53 UTC, LeeWannacott requested changes
If you could change date format and add some real people; so then you can add some real dates that would be great :+1: 

Like for example:
![table-screen](https://user-images.githubusercontent.com/49783296/107300088-a8f6df00-6add-11eb-80eb-4536a9c14c41.png)

2021-02-09 00:53 UTC, LeeWannacott commented on README.md
> +            <td>Micheal</td>
Minor typo: Micheal is spelled Michael in Michael Jackson's name.

2021-02-09 00:53 UTC, LeeWannacott commented on README.md
> +            <td>1964</td>
MJ was born 1958. For dates to showcase what table sort can do, I think we can change Date to the format: 1958/8/29 and use different delimiters for the different people e.g 1958-8-29 1958.8.29 etc. . So if we change all the dates in the table to this format and perhaps to real people: like for example changing Bach Frank to Benjamin Franklin or Sebastian Bach then you can put a real date.

Ben 10 is fine though can just make up a date for him; maybe when the show started?, or something.

2021-02-21 13:34 UTC, anupshrestha11 commented
I will make changes to the table.

2021-02-23 17:55 UTC, merged

2021-02-23 17:58 UTC, LeeWannacott commented
Thanks. Commit landed in 387ef05